services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
    ports:
      - ${AGENT_PORT}:4242
  mongo:
    command: mongod
    image: mongo:4.0.0
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  dff-program-y-skill:
  sentseg:
  convers-evaluation-selector:
  dff-intent-responder-skill:
  intent-catcher:
  badlisted-words:
  spelling-preprocessing:
  image-captioning:
    environment:
      - CUDA_VISIBLE_DEVICES=0
version: '3.7'